[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pylsp-mypy]
enabled = false
live_mode = false
strict = false

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"