[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "data_science_utils"
version = "0.99.0"

[tool.setuptools.packages.find]
where = ["src"]
