This is a repository consisting of utility functions in the authors personal data science career. This README will give a high level overview of the modules involved which glues all aspects of the utility files together for the authors personal productivity.

* Datasets

A common way to compare models is to run a different model on a public, well-known datasets. Furthermore, some papers will go through the same preprocessing steps as each other. The datasets module will contain functions which download the datasets and perform certain preprocessing steps so that one may import the datasets easily.

* Models

* Pipelines

This module contains code which brings together multiple modules which need to work together.
Testing this module entails 

* TODO 

* TODO 

* Organizational Principles

=data_science_utils/*= Contains modules

Every individual module is tested in =tests/unit/test_*.py=
Every individual module is tested in =tests/unit/test_*.py=

=cache= Holds data and model data (like weights)
=channels.scm= + =.direnv= + =.envrc= + =.guix= + =guix-channel=

* Dynamical Systems

In this module, there are several types of dynamical systems sharing a somewhat unified interface.

Simply put, a dynamical system is defined by its trajectory. There are several independent adjectives by which a dynamical system can be described. It can be discrete or continuous. Discrete systems can be further stratified into invertable or noninvertible systems. It can be deterministic or stochastic. It can operate over swarms or individuals. It can operate over random finite sets or on a constant cardinality of states. Each of these adjectives subtly change the function signature for their respective forward equations, hence the =trajectory= method.
